// Generated by `jobkit portfolio build` from catalog/portfolio.yaml in the
// data repo. Edit that file, not this one.
window.PORTFOLIO = {
  "name": "Muhammad Uzair",
  "position": "Senior Software Engineer. Backend systems and production AI on AWS.",
  "intro": [
    "I build the backend and the AI layer of products that handle real money, real identities and real health data: Pakistan's first passwordless digital identity platform, a multi-tenant workforce platform serving up to 15 organisations and nearly 30,000 people, and two AI-powered health products live in the US App Store.",
    "TypeScript and Node.js on AWS, serverless and event-driven by default. LLM applications with grounding, guardrails and evals that hold up in production. I design the cloud architecture, run what I ship, and treat the bill as an engineering input."
  ],
  "glance": [
    {
      "k": "Role",
      "v": "Senior Software Engineer: backend, cloud and AI engineering"
    },
    {
      "k": "Experience",
      "v": "6+ years hands-on, senior roles at two product companies"
    },
    {
      "k": "Stack",
      "v": "TypeScript, Node.js, AWS serverless (Lambda, Step Functions, SQS, EventBridge, AppSync, CDK), PostgreSQL; LLM applications with RAG, agents and evals"
    },
    {
      "k": "Location",
      "v": "Pakistan (UTC+5). Remote-first for years with North American teams; overlaps US and EU working hours, flexible to the team's day"
    },
    {
      "k": "Open to",
      "v": "Senior Software Engineer, Backend Engineer and AI Engineer roles at remote product companies in the EU, UK and US; relocation possible"
    }
  ],
  "headlineFigures": [
    {
      "value": "$40k+ / yr",
      "label": "cloud and vendor spend cut or avoided across two platforms"
    },
    {
      "value": "2",
      "label": "AI-powered health products live in the US App Store"
    },
    {
      "value": "30,000",
      "label": "people on a B2B workforce platform serving up to 15 client organisations"
    }
  ],
  "heroDiagram": {
    "nodes": [
      {
        "id": "clients",
        "label": "Web, mobile and voice clients",
        "x": 0,
        "y": 0,
        "point": 0
      },
      {
        "id": "api",
        "label": "API: GraphQL and REST",
        "x": 1,
        "y": 0,
        "point": 0
      },
      {
        "id": "svc",
        "label": "Services: Lambda, Node.js",
        "x": 2,
        "y": 0,
        "point": 0
      },
      {
        "id": "data",
        "label": "PostgreSQL, time series, vector search",
        "x": 3,
        "y": 0,
        "point": 0
      },
      {
        "id": "ops",
        "label": "Observability, alerts, on-call",
        "x": 1,
        "y": 1,
        "point": 0
      },
      {
        "id": "queue",
        "label": "Queues and workflows: SQS, Step Functions",
        "x": 2,
        "y": 1,
        "point": 0
      },
      {
        "id": "llm",
        "label": "LLM layer: grounding, guardrails, failover, cost caps",
        "x": 3,
        "y": 1,
        "point": 0
      }
    ],
    "edges": [
      [
        "clients",
        "api"
      ],
      [
        "api",
        "svc"
      ],
      [
        "svc",
        "data"
      ],
      [
        "svc",
        "queue"
      ],
      [
        "queue",
        "llm"
      ],
      [
        "llm",
        "data"
      ],
      [
        "api",
        "ops"
      ]
    ],
    "path": [
      "clients",
      "api",
      "svc",
      "queue",
      "llm",
      "data"
    ],
    "caption": "The shape of what I build: an event-driven backend on AWS with an AI layer that is safe to run in production. Every box is something I have shipped."
  },
  "contact": {
    "email": "uzairkhattak004@gmail.com",
    "linkedin": "https://www.linkedin.com/in/uzair004",
    "github": "https://github.com/uzair004",
    "emailSubject": "Senior engineer role"
  },
  "work": [
    {
      "id": "meraid",
      "src": "ce-sM39Rn_3 ce-YMqo83tC ce-nyCkCLiv ce-TJQfg4d7 ce-tM2FuLFx",
      "title": "meraID",
      "org": "Productbox",
      "dates": "2021 to 2024",
      "place": "Islamabad",
      "tagline": "Pakistan's first passwordless digital identity platform, in the category of Sweden's BankID: one verified identity to sign in, authorise transactions and sign documents across partner services.",
      "figures": [
        {
          "value": "~10,000",
          "label": "identity verifications processed"
        },
        {
          "value": "5",
          "label": "partner services, including a university, an online shop and a hiring product"
        },
        {
          "value": "9 s to 1 s",
          "label": "API response time on live traffic"
        }
      ],
      "points": [
        "Replaced passwords with a device-bound identity: partner services authenticate people, approve transactions and collect signatures through one integration, and the signing key never leaves the person's phone.",
        "Turned identity verification from minutes of manual document checking per applicant into an automated pipeline: web automation of the national identity portal with English and Urdu OCR.",
        "Designed and shipped the partner-facing API with per-partner key exchange, and the integration guide that partner engineering teams built against.",
        "Packaged the platform for on-premise deployment so banks with strict hosting rules could adopt it: the same services as containers with self-hosted databases and queues in place of managed AWS."
      ],
      "built": "Owned the backend and the AWS architecture across five event-driven serverless services, and re-architected the core when the requirements changed.",
      "stack": [
        "Node.js",
        "AWS Lambda",
        "DynamoDB",
        "Serverless Framework",
        "Puppeteer",
        "Python",
        "OpenCV",
        "Tesseract",
        "Docker"
      ],
      "diagram": {
        "nodes": [
          {
            "id": "partner",
            "label": "Partner backend",
            "x": 0,
            "y": 0,
            "point": 2
          },
          {
            "id": "api",
            "label": "Relying-party API",
            "x": 1,
            "y": 0,
            "point": 2
          },
          {
            "id": "core",
            "label": "Identity services",
            "x": 2,
            "y": 0,
            "point": 0
          },
          {
            "id": "app",
            "label": "meraID app, signing key",
            "x": 3,
            "y": 0,
            "point": 0
          },
          {
            "id": "verify",
            "label": "Portal automation + OCR",
            "x": 2,
            "y": 1,
            "point": 1
          }
        ],
        "edges": [
          [
            "partner",
            "api"
          ],
          [
            "api",
            "core"
          ],
          [
            "core",
            "app"
          ],
          [
            "core",
            "verify"
          ]
        ],
        "path": [
          "partner",
          "api",
          "core",
          "app"
        ],
        "caption": "A partner asks meraID to authenticate a person; the person approves on their phone."
      }
    },
    {
      "id": "digistaff",
      "src": "ce-IRFJnj6e ce-A2QHsxP3 ce-PFpUI6l2 ce-KrueF7_c ce-2gutVygK",
      "title": "DigiStaff",
      "org": "DigiStaff",
      "dates": "Nov 2024 to Sep 2025",
      "place": "Canada, remote",
      "tagline": "Multi-tenant workforce platform for temporary staffing in Canada: scheduling, worker check-in, payroll and billing for up to 15 client organisations.",
      "figures": [
        {
          "value": "15k to 30k",
          "label": "users, and client organisations from 5 to 15"
        },
        {
          "value": "45%",
          "label": "off the AWS bill, about $23k a year"
        },
        {
          "value": "1 to 5 min",
          "label": "downtime to move a live production database"
        }
      ],
      "points": [
        "Cut the AWS bill by 45%, about $23,000 a year: moved the production database off end-of-life Aurora Serverless v1 to v2 with one to five minutes of downtime and no application change, then consolidated servers. Written up as a three-part series on dev.to.",
        "Gave supervisors plain-language candidate search: an LLM reads each résumé into structured data in a vector database, so a plain sentence finds candidates that rigid filter forms missed. Adopted across client organisations.",
        "Made payroll and billing safe to retry: a rerun or a redelivered message never pays a worker twice or charges a client twice.",
        "Shipped three ways for workers to clock in, including fingerprint hardware shared across tenants and a PIN route for workers without a phone, and removed the per-client tablet purchase that slowed onboarding."
      ],
      "built": "Led backend engineering on AWS: AppSync GraphQL over Lambda services in CDK, a master-pool Aurora PostgreSQL with a database per tenant. Hired one engineer and mentored two.",
      "stack": [
        "TypeScript",
        "AWS Lambda",
        "AppSync",
        "Step Functions",
        "SQS",
        "EventBridge",
        "Aurora PostgreSQL",
        "AWS CDK",
        "Weaviate",
        "Gemini"
      ],
      "diagram": {
        "nodes": [
          {
            "id": "kiosk",
            "label": "Kiosk / fingerprint",
            "x": 0,
            "y": 0,
            "point": 3
          },
          {
            "id": "appsync",
            "label": "AppSync GraphQL",
            "x": 1,
            "y": 0,
            "point": 3
          },
          {
            "id": "shift",
            "label": "Shift service",
            "x": 2,
            "y": 0,
            "point": 3
          },
          {
            "id": "aurora",
            "label": "Aurora PostgreSQL v2",
            "x": 3,
            "y": 0,
            "point": 0
          },
          {
            "id": "search",
            "label": "Résumé search, Weaviate",
            "x": 1,
            "y": 1,
            "point": 1
          },
          {
            "id": "queue",
            "label": "SQS",
            "x": 2,
            "y": 1,
            "point": 2
          },
          {
            "id": "payroll",
            "label": "Payroll, idempotent",
            "x": 3,
            "y": 1,
            "point": 2
          }
        ],
        "edges": [
          [
            "kiosk",
            "appsync"
          ],
          [
            "appsync",
            "shift"
          ],
          [
            "shift",
            "aurora"
          ],
          [
            "shift",
            "queue"
          ],
          [
            "queue",
            "payroll"
          ],
          [
            "payroll",
            "aurora"
          ],
          [
            "appsync",
            "search"
          ]
        ],
        "path": [
          "kiosk",
          "appsync",
          "shift",
          "queue",
          "payroll",
          "aurora"
        ],
        "caption": "A worker clocks in and the shift becomes payroll."
      }
    },
    {
      "id": "passport",
      "src": "ce-lwCfF3br ce-BtuH1a4N",
      "title": "Augi Passport",
      "org": "Algorithm",
      "dates": "Sep 2025 to present",
      "place": "US market, remote",
      "tagline": "AI-powered consumer health platform for the US market: wearable data, medical records and an AI assistant on one timeline.",
      "figures": [
        {
          "value": "15,000",
          "label": "wearable samples per person per day"
        },
        {
          "value": "90%",
          "label": "less storage for health time series"
        },
        {
          "value": "$20k / yr",
          "label": "vendor spend avoided by building the realtime data path"
        }
      ],
      "points": [
        "Built the wearable data platform on TimescaleDB: up to 15,000 samples per person per day from Apple Watch, Garmin, Oura, Fitbit and WHOOP, aggregated correctly across time zones, with storage cut by up to 90%. It shipped and carried real users' health data.",
        "Chose build over buy for the realtime data path after evaluating six options: hourly granularity and local raw data the vendor could not offer, and about $20,000 a year in vendor fees avoided.",
        "Connected medical records through a FHIR aggregator covering Epic, Cerner and Athenahealth networks, so a person's records and device data sit on one timeline.",
        "Made the AI assistant safe to operate: spend capped per person and per service, every request attributable, limiters that fail open; right to erasure across four data stores."
      ],
      "built": "Backend engineer across the Node/Express API and the React Native client; built the time-series platform and the wearable ingestion path.",
      "stack": [
        "Node.js",
        "Express",
        "PostgreSQL",
        "TimescaleDB",
        "MongoDB",
        "Redis",
        "BullMQ",
        "React Native",
        "Claude"
      ],
      "diagram": {
        "nodes": [
          {
            "id": "watch",
            "label": "Watch, ring, phone",
            "x": 0,
            "y": 0,
            "point": 0
          },
          {
            "id": "hooks",
            "label": "Webhooks + HealthKit",
            "x": 1,
            "y": 0,
            "point": 0
          },
          {
            "id": "api",
            "label": "Express API",
            "x": 2,
            "y": 0,
            "point": 0
          },
          {
            "id": "ts",
            "label": "TimescaleDB, compressed",
            "x": 3,
            "y": 0,
            "point": 1
          },
          {
            "id": "ehr",
            "label": "Epic / Cerner via FHIR",
            "x": 1,
            "y": 1,
            "point": 2
          },
          {
            "id": "ai",
            "label": "Assistant, capped spend",
            "x": 3,
            "y": 1,
            "point": 3
          }
        ],
        "edges": [
          [
            "watch",
            "hooks"
          ],
          [
            "hooks",
            "api"
          ],
          [
            "api",
            "ts"
          ],
          [
            "ehr",
            "api"
          ],
          [
            "ts",
            "ai"
          ]
        ],
        "path": [
          "watch",
          "hooks",
          "api",
          "ts",
          "ai"
        ],
        "caption": "A heart-rate sample lands on the right day and the assistant can answer from it."
      }
    },
    {
      "id": "echo",
      "src": "ce-w6SL5xxf",
      "title": "Augi Echo",
      "org": "Algorithm",
      "dates": "2026",
      "place": "US market, remote",
      "tagline": "AI-first care companion for parents of newly diagnosed autistic children, with a live view for their clinician. Live on the App Store.",
      "figures": [
        {
          "value": "10 s",
          "label": "to log an observation by voice, down from minutes of typing"
        },
        {
          "value": "6",
          "label": "LLM features on one shared provider layer"
        }
      ],
      "points": [
        "Parents speak; the app turns it into plain-language records, next steps and a weekly recap, and their doctor sees a structured view of the child between appointments.",
        "Grounded clinician chat that cites the child's own records and peer-reviewed literature, with prompt-injection and scope guardrails and rate limiting: an answer a doctor can rely on inside a fifteen-minute appointment.",
        "One provider layer across Anthropic and OpenAI for streaming, retries, overload deferral and kill switches, so a model swap or a cost limit is a one-line change rather than a rewrite.",
        "Built for daily releases: in-flight AI work finishes before a deploy, a slow provider cannot slow the rest of the app, and stranded jobs resume on their own."
      ],
      "built": "Built the AI layer end to end and most of the parent app's server: voice log, follow-up tasks, milestones, resource library, summaries, weekly recap, email verification.",
      "stack": [
        "NestJS",
        "MongoDB",
        "Redis",
        "BullMQ",
        "Anthropic",
        "OpenAI",
        "Expo / React Native"
      ],
      "diagram": {
        "nodes": [
          {
            "id": "voice",
            "label": "Parent's voice note",
            "x": 0,
            "y": 0,
            "point": 0
          },
          {
            "id": "stt",
            "label": "Transcribe, retried",
            "x": 1,
            "y": 0,
            "point": 3
          },
          {
            "id": "llm",
            "label": "LLM structure",
            "x": 2,
            "y": 0,
            "point": 2
          },
          {
            "id": "rec",
            "label": "Records + recap",
            "x": 3,
            "y": 0,
            "point": 0
          },
          {
            "id": "queue",
            "label": "Per-provider queues",
            "x": 2,
            "y": 1,
            "point": 3
          },
          {
            "id": "chat",
            "label": "Grounded clinician chat",
            "x": 3,
            "y": 1,
            "point": 1
          }
        ],
        "edges": [
          [
            "voice",
            "stt"
          ],
          [
            "stt",
            "llm"
          ],
          [
            "llm",
            "rec"
          ],
          [
            "llm",
            "queue"
          ],
          [
            "rec",
            "chat"
          ]
        ],
        "path": [
          "voice",
          "stt",
          "llm",
          "rec",
          "chat"
        ],
        "caption": "Ten seconds of speech becomes a record the doctor can question."
      }
    },
    {
      "id": "donna",
      "src": "ce-82w_jIec",
      "title": "DonnaAI",
      "org": "Algorithm, for a client",
      "dates": "Sep 2025",
      "place": "remote",
      "tagline": "AI phone receptionist for service businesses: a voice agent answers the call and books the job into the company's CRM, or hands over to a person.",
      "figures": [],
      "points": [
        "Every finished call becomes a booked job in the customer's CRM with nobody re-keying it: a typed integration that surfaces vendor failures as clear errors, retries with backoff and keeps credentials out of logs.",
        "Twilio carries the call, Retell runs speech, the product owns the LLM conversation with tool calling; fixed a production defect in the call-transfer path."
      ],
      "built": "Built the CRM integration service.",
      "stack": [
        "TypeScript",
        "Express",
        "Twilio",
        "Retell",
        "OpenAI"
      ],
      "diagram": {
        "nodes": [
          {
            "id": "caller",
            "label": "Caller",
            "x": 0,
            "y": 0,
            "point": 1
          },
          {
            "id": "voice",
            "label": "Twilio + Retell",
            "x": 1,
            "y": 0,
            "point": 1
          },
          {
            "id": "agent",
            "label": "LLM agent",
            "x": 2,
            "y": 0,
            "point": 1
          },
          {
            "id": "proxy",
            "label": "Typed CRM integration",
            "x": 3,
            "y": 0,
            "point": 0
          },
          {
            "id": "crm",
            "label": "ServiceMonster CRM",
            "x": 4,
            "y": 0,
            "point": 0
          }
        ],
        "edges": [
          [
            "caller",
            "voice"
          ],
          [
            "voice",
            "agent"
          ],
          [
            "agent",
            "proxy"
          ],
          [
            "proxy",
            "crm"
          ]
        ],
        "path": [
          "caller",
          "voice",
          "agent",
          "proxy",
          "crm"
        ],
        "caption": "A phone call becomes a job in the CRM."
      }
    },
    {
      "id": "akash",
      "src": "ce-qcFJU21z",
      "title": "AKASH",
      "org": "Freelance",
      "dates": "Jan to Aug 2026",
      "place": "remote",
      "tagline": "Marketplace for live video wellness sessions: clients book practitioners, sessions run as video calls, and money moves safely through the platform.",
      "figures": [],
      "points": [
        "Payments end to end on Stripe: wallets, payouts, transactions, commission and accounting, with webhook handling that keeps every balance right.",
        "Live sessions on Agora with real-time updates over Socket.IO and Redis; background work on BullMQ with a dedicated session worker.",
        "Shipped with CI, database migrations and a deploy path the client runs without me, plus most of the React admin dashboard."
      ],
      "built": "Built and ran the backend for a freelance client: Express on PostgreSQL with Prisma, Redis, S3.",
      "stack": [
        "Node.js",
        "Express",
        "PostgreSQL",
        "Prisma",
        "Stripe",
        "Redis",
        "BullMQ",
        "Agora",
        "Socket.IO",
        "AWS S3",
        "Docker"
      ],
      "diagram": {
        "nodes": [
          {
            "id": "client",
            "label": "Client books",
            "x": 0,
            "y": 0,
            "point": 1
          },
          {
            "id": "api",
            "label": "Express API",
            "x": 1,
            "y": 0,
            "point": 2
          },
          {
            "id": "stripe",
            "label": "Stripe: wallet, payout",
            "x": 2,
            "y": 0,
            "point": 0
          },
          {
            "id": "video",
            "label": "Agora session",
            "x": 2,
            "y": 1,
            "point": 1
          },
          {
            "id": "worker",
            "label": "BullMQ session worker",
            "x": 1,
            "y": 1,
            "point": 1
          }
        ],
        "edges": [
          [
            "client",
            "api"
          ],
          [
            "api",
            "stripe"
          ],
          [
            "api",
            "video"
          ],
          [
            "api",
            "worker"
          ]
        ],
        "path": [
          "client",
          "api",
          "stripe"
        ],
        "caption": "A booking becomes a session and a payout."
      }
    }
  ],
  "earlier": [
    {
      "src": "ce-0CPCdAuq",
      "title": "Lettus Kitchens",
      "org": "Productbox",
      "dates": "2021 to 2022",
      "text": "Supply-chain and inventory backend for multi-city cloud kitchens: real-time stock and order tracking with transactional updates, so two orders never claim the same stock. Node.js, Express, MySQL on AWS."
    },
    {
      "src": "ce-UslUFJHY",
      "title": "jobApp",
      "org": "Productbox",
      "dates": "2022",
      "text": "Hiring portal with configurable pipelines, stage boards, score cards and automations, with meraID for passwordless sign-in. Serverless AWS, DynamoDB."
    },
    {
      "src": "ce-FbsdWxS5",
      "title": "MonsterPool",
      "org": "Productbox",
      "dates": "2021",
      "text": "Interest-free peer-to-peer lending for the US market with Plaid bank integration; shipped the tips feature end to end. Express, MySQL."
    }
  ],
  "oss": [
    {
      "name": "pennyllm-router",
      "url": "https://github.com/uzair004/pennyllm-router",
      "src": "ce-4d7Af3qQ",
      "text": "A TypeScript router between application code and LLM providers: an ordered model chain with two-tier failover (rotate keys within a provider, then move to the next), provider-error classification that never leaks a vendor SDK's error type, per-key cooldowns with exponential backoff, and a rolling-window circuit breaker with half-open recovery."
    },
    {
      "name": "candidate-finder-ai",
      "url": "https://github.com/uzair004/candidate-finder-ai",
      "src": "ce-_CntmEq3",
      "text": "Résumé ingestion and semantic candidate search on AWS: a five-stage Step Functions pipeline fed by SQS through EventBridge Pipes, hybrid BM25 plus vector search in Weaviate joined back to Postgres, behind an AppSync GraphQL API. Runs locally on Docker with Ollama at zero API cost. The open-source sibling of the pipeline shipped at DigiStaff."
    },
    {
      "name": "event-driven-serverless-app",
      "url": "https://github.com/uzair004/event-driven-serverless-app",
      "src": "ce-qtooLiR2",
      "text": "Reference event-driven backend on AWS: Lambda behind API Gateway, DynamoDB, SQS, Serverless Framework and GitHub Actions, in clean architecture so the logic tests without the cloud."
    },
    {
      "name": "missing-person-finder",
      "url": "https://github.com/uzair004/missing-person-finder",
      "src": "ce-UQgVLji9",
      "text": "Matches an uploaded photo against stored face embeddings, running face recognition server-side in Node (TensorFlow.js with MediaPipe models), 1024-dimension embeddings at a 0.55 similarity threshold."
    },
    {
      "name": "nest-sse-example",
      "url": "https://github.com/uzair004/nest-sse-example",
      "src": "ce-eoguJL4A",
      "text": "Server-sent events in NestJS from an RxJS observable, the primitive the streaming work at Augi later relied on."
    },
    {
      "name": "node-clean-boilerplate",
      "url": "https://github.com/uzair004/node-clean-boilerplate",
      "src": "ce-0db_7MdU",
      "text": "Node.js starting point on clean architecture and domain-driven design."
    }
  ],
  "writing": {
    "title": "Aurora Serverless v1 to v2, a migration series",
    "src": "ce-2gutVygK",
    "text": "Written while executing the DigiStaff production migration: what changed between the versions, two strategies compared on six axes, and the snapshot-and-restore route step by step with its rollback plan.",
    "articles": [
      {
        "title": "Aurora Serverless v2 vs. v1: a concise comparison of key differences",
        "url": "https://dev.to/uzair004/aurora-serverless-v2-vs-v1-a-concise-comparison-of-key-differences-2103",
        "date": "Feb 2025"
      },
      {
        "title": "Migrate Aurora v1: strategies explained",
        "url": "https://dev.to/uzair004/migrate-aurora-v1-strategies-explained-3e7d",
        "date": "Mar 2025"
      },
      {
        "title": "Aurora v1 to v2, migrating via snapshot and restore: a step-by-step guide",
        "url": "https://dev.to/uzair004/aurora-v1-to-v2-migrating-via-snapshot-and-restore-a-step-by-step-guide-5c02",
        "date": "Mar 2025"
      }
    ]
  },
  "timeline": [
    {
      "role": "Senior Software Engineer",
      "org": "Algorithm",
      "dates": "Sep 2025 to present",
      "place": "Remote, US products",
      "note": "Augi Passport, Augi Echo, DonnaAI. Architecture, code review, mentoring, incident response.",
      "src": "ce-BtuH1a4N"
    },
    {
      "role": "Senior Backend Engineer",
      "org": "DigiStaff",
      "dates": "Nov 2024 to Sep 2025",
      "place": "Remote, Canada",
      "note": "Led backend engineering on the workforce platform.",
      "src": "ce-IRFJnj6e"
    },
    {
      "role": "Backend Engineer",
      "org": "Productbox",
      "dates": "Oct 2021 to Nov 2024",
      "place": "Islamabad",
      "note": "meraID backend and AWS architecture; Lettus Kitchens and jobApp backends.",
      "src": "ce-YMqo83tC"
    },
    {
      "role": "Junior Backend Engineer",
      "org": "Productbox",
      "dates": "Jun to Oct 2021",
      "place": "Islamabad",
      "note": "MonsterPool fintech backend.",
      "src": "ce-Paav8rP2"
    },
    {
      "role": "Freelance Node.js Developer",
      "org": "Fiverr",
      "dates": "Mar to Jun 2021",
      "place": "Remote",
      "note": "Marketplace backend for handmade-product sellers: Node.js, MongoDB, Redis, multi-currency.",
      "src": "ce-cYtQzrLM"
    }
  ],
  "education": [
    {
      "title": "BSc Computer Science",
      "org": "University of Peshawar",
      "dates": "2017 to 2021",
      "note": "GPA 3.78 / 4.0",
      "src": "ce-DoQ_rnvC"
    },
    {
      "title": "Full Stack Engineer, volunteer",
      "org": "University of Peshawar",
      "dates": "Aug 2020 to Jan 2021",
      "note": "First professional role, during the final year.",
      "src": "ce-T7ouRS1X"
    }
  ],
  "technologies": [
    {
      "group": "Languages",
      "items": [
        "TypeScript",
        "JavaScript",
        "SQL",
        "Python"
      ]
    },
    {
      "group": "Backend",
      "items": [
        "Node.js",
        "Express",
        "NestJS",
        "GraphQL (AppSync)",
        "REST",
        "WebSocket",
        "Server-sent events",
        "Clean architecture",
        "Multi-tenant SaaS"
      ]
    },
    {
      "group": "AWS and cloud",
      "items": [
        "Lambda",
        "Step Functions",
        "SQS",
        "EventBridge",
        "AppSync",
        "API Gateway",
        "Aurora",
        "DynamoDB",
        "S3",
        "SES",
        "IoT Core",
        "EC2",
        "CDK",
        "Serverless Framework",
        "CloudWatch",
        "Firebase",
        "GCP Functions"
      ]
    },
    {
      "group": "Data",
      "items": [
        "PostgreSQL",
        "Aurora Serverless",
        "TimescaleDB",
        "DynamoDB",
        "MongoDB",
        "MySQL",
        "Redis",
        "Weaviate",
        "Prisma",
        "Sequelize"
      ]
    },
    {
      "group": "AI",
      "items": [
        "Anthropic, OpenAI and Gemini APIs",
        "RAG and grounding",
        "Embeddings and hybrid search",
        "LLM extraction under schemas",
        "Guardrails and evals",
        "Provider failover and cost caps",
        "Voice agents and tool calling",
        "Vercel AI SDK"
      ]
    },
    {
      "group": "Product and integrations",
      "items": [
        "React Native (Expo)",
        "React",
        "Next.js",
        "Stripe",
        "Plaid",
        "Twilio",
        "FHIR"
      ]
    },
    {
      "group": "Operations",
      "items": [
        "Docker",
        "GitHub Actions",
        "Infrastructure as code",
        "Observability and on-call",
        "Live database migrations",
        "Cloud cost engineering"
      ]
    }
  ],
  "how": [
    {
      "heading": "Cloud architecture that pays for itself",
      "icon": "ops",
      "lines": [
        "Serverless and event-driven on AWS: Lambda, Step Functions, SQS, EventBridge, AppSync, CDK",
        "Infrastructure as code, CI/CD, release trains to staging and production",
        "$40k+ a year in cloud and vendor spend cut or avoided, with receipts"
      ]
    },
    {
      "heading": "Correct with real money and real data",
      "icon": "ledger",
      "lines": [
        "Payments, payroll and billing that are safe to retry",
        "Identity and health data handled with erasure, audit and residency in mind",
        "Database migrations on live traffic with a rollback plan"
      ]
    },
    {
      "heading": "AI that survives production",
      "icon": "ai",
      "lines": [
        "Grounding and citations over private data",
        "Guardrails, evals and hard cost ceilings",
        "Provider abstraction so the feature outlives the vendor"
      ]
    },
    {
      "heading": "Remote by default",
      "icon": "globe",
      "lines": [
        "Years of remote work with North American teams, overlapping US and EU hours",
        "Written proposals compared on their trade-offs before anything is built",
        "Code review, incident response and mentoring junior engineers"
      ]
    }
  ],
  "cta": {
    "heading": "Hiring a senior backend, cloud or AI engineer?",
    "text": "Send the role. I reply with how this work maps to it, and where it does not.",
    "resumeLabel": "Résumé (PDF)"
  }
};
